# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  - group: AzureCredentials

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: ApplyTerraform
  displayName: Apply Terraform
  steps:
  - script: |
      ls /home/linuxbrew/.linuxbrew/bin
      ls /home/linuxbrew/.linuxbrew/sbin
      ls /usr/share/rust/.cargo/bin
      ls /home/runner/.config/composer/vendor/bin
      ls /home/runner/.dotnet/tools
      ls /snap/bin
      ls /usr/local/sbin
      ls /usr/local/bin
      ls /usr/sbin
      ls /usr/bin
      ls /sbin
      ls /bin
      ls /usr/games
      ls /usr/local/games
      ls /snap/bin
    displayName: Download & install Terraform v0.13.2

  - script: terraform init
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
    displayName: 'Initialize Terraform'
    env:
      ARM_CLIENT_ID: '$(Azure.ClientId)'
      ARM_CLIENT_SECRET: '$(Azure.ClientSecret)'
      ARM_SUBSCRIPTION_ID: '$(Azure.SubscriptionId)'
      ARM_TENANT_ID: '$(Azure.TenantId)'
  
  - script: terraform apply -auto-approve
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
    displayName: 'Apply Terraform'
    env:
      ARM_CLIENT_ID: '$(Azure.ClientId)'
      ARM_CLIENT_SECRET: '$(Azure.ClientSecret)'
      ARM_SUBSCRIPTION_ID: '$(Azure.SubscriptionId)'
      ARM_TENANT_ID: '$(Azure.TenantId)'
