trigger:
  - master
  
variables:
  - group: AzureCredentials

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: ApplyTerraform
  displayName: Apply Terraform
  steps:
  - script: terraform init
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
    displayName: 'Terraform - Initialize'
    env:
      ARM_CLIENT_ID: '$(Azure.ClientId)'
      ARM_CLIENT_SECRET: '$(Azure.ClientSecret)'
      ARM_SUBSCRIPTION_ID: '$(Azure.SubscriptionId)'
      ARM_TENANT_ID: '$(Azure.TenantId)'
  
  - script: terraform apply -auto-approve
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
    displayName: 'Terraform - Apply'
    env:
      ARM_CLIENT_ID: '$(Azure.ClientId)'
      ARM_CLIENT_SECRET: '$(Azure.ClientSecret)'
      ARM_SUBSCRIPTION_ID: '$(Azure.SubscriptionId)'
      ARM_TENANT_ID: '$(Azure.TenantId)'
